'use client';
import { useEffect,useMemo,useState } from 'react'; import Link from 'next/link'; import { Nav } from '@/components/Nav'; import { AuthGuard } from '@/components/AuthGuard'; import { GigCard } from '@/components/GigCard'; import { Loading } from '@/components/Loading'; import { EmptyState } from '@/components/EmptyState'; import { supabase } from '@/lib/supabase'; import type { Gig } from '@/lib/types';
export default function Home(){const [gigs,setGigs]=useState<Gig[]>([]);const [q,setQ]=useState('');const [mine,setMine]=useState(false);const [rating,setRating]=useState(0);const [loading,setLoading]=useState(true);const [userId,setUserId]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id||'');const {data}=await supabase.from('gigs').select('*, profiles(username,display_name,avatar_url), review_likes(user_id), comments(id)').order('event_date',{ascending:false});setGigs((data||[]) as Gig[]);setLoading(false)})()},[]);
 const shown=useMemo(()=>gigs.filter(g=>{const text=(g.artist_name+' '+g.venue_name+' '+(g.festival_name||'')+' '+(g.city||'')).toLowerCase();return text.includes(q.toLowerCase())&&(!mine||g.user_id===userId)&&(!rating||g.overall_rating>=rating)}),[gigs,q,mine,rating,userId]);
 const mineGigs=gigs.filter(g=>g.user_id===userId);const avg=mineGigs.length?(mineGigs.reduce((a,g)=>a+g.overall_rating,0)/mineGigs.length).toFixed(1):'—';
 return <AuthGuard><Nav/><main className="shell"><section className="hero"><div><div className="eyebrow">// every show, one torn stub at a time</div><h1>YOUR <span className="accent">ARCHIVE</span></h1><p className="hero-copy">Rate the night, keep the memory, find the next one.</p></div><Link className="btn" href="/gigs/new">+ Log a gig</Link></section>
 <div className="statcards"><div className="statcard"><strong>{mineGigs.length}</strong>your gigs</div><div className="statcard"><strong>{new Set(mineGigs.map(g=>g.artist_name.toLowerCase())).size}</strong>artists</div><div className="statcard"><strong>{new Set(mineGigs.map(g=>g.venue_name.toLowerCase())).size}</strong>venues</div><div className="statcard"><strong>{avg}</strong>average rating</div></div>
 <div className="toolbar"><input className="input" placeholder="Search artist, venue, city or festival…" value={q} onChange={e=>setQ(e.target.value)}/><select className="input compact" value={rating} onChange={e=>setRating(Number(e.target.value))}><option value="0">Any rating</option><option value="5">5 stars</option><option value="4">4+ stars</option><option value="3">3+ stars</option></select><label className="toggle"><input type="checkbox" checked={mine} onChange={e=>setMine(e.target.checked)}/> Mine only</label></div>
 {loading?<Loading/>:shown.length?<div className="grid">{shown.map(g=><GigCard key={g.id} gig={g}/>)}</div>:<EmptyState title="No stubs found" body={q||mine||rating?'Try changing your filters.':'Your archive is waiting for its first memory.'} href={!q&&!mine&&!rating?'/gigs/new':undefined} label="Log your first gig"/>}
 </main></AuthGuard>}
