'use client';
import { useEffect,useState } from 'react'; import { useParams,useRouter } from 'next/navigation'; import Link from 'next/link'; import { Trash2,Pencil,ExternalLink } from 'lucide-react'; import { Nav } from '@/components/Nav'; import { AuthGuard } from '@/components/AuthGuard'; import { Stars } from '@/components/Stars'; import { LikeButton } from '@/components/LikeButton'; import { PhotoUploader } from '@/components/PhotoUploader'; import { Loading } from '@/components/Loading'; import { supabase } from '@/lib/supabase'; import type { Comment,Gig } from '@/lib/types';
const ratingFields=['overall','performance','sound','crowd','venue','value'] as const;
export default function GigDetail(){const {id}=useParams<{id:string}>();const router=useRouter();const [gig,setGig]=useState<Gig|null>(null);const [userId,setUserId]=useState('');const [editing,setEditing]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [comments,setComments]=useState<Comment[]>([]);const [comment,setComment]=useState('');const [photos,setPhotos]=useState<string[]>([]);const [ratings,setRatings]=useState<Record<string,number>>({});
 async function load(){const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id||'');const [{data:g,error},{data:c}]=await Promise.all([supabase.from('gigs').select('*, profiles(username,display_name,avatar_url)').eq('id',id).single(),supabase.from('comments').select('*, profiles(username,display_name)').eq('gig_id',id).order('created_at')]);if(error)setError(error.message);else{setGig(g as Gig);setPhotos(g.photo_urls||[]);setRatings({overall:g.overall_rating,performance:g.performance_rating||0,sound:g.sound_rating||0,crowd:g.crowd_rating||0,venue:g.venue_rating||0,value:g.value_rating||0})}setComments((c||[]) as Comment[]);setLoading(false)}
 useEffect(()=>{load()},[id]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!gig)return;const fd=new FormData(e.currentTarget);const {error}=await supabase.from('gigs').update({artist_name:fd.get('artist'),venue_name:fd.get('venue'),festival_name:fd.get('festival')||null,event_date:fd.get('date'),event_type:fd.get('event_type'),city:fd.get('city')||null,country:fd.get('country')||null,ticket_url:fd.get('ticket_url')||null,photo_urls:photos,is_public:fd.get('is_public')==='on',overall_rating:ratings.overall,performance_rating:ratings.performance||null,sound_rating:ratings.sound||null,crowd_rating:ratings.crowd||null,venue_rating:ratings.venue||null,value_rating:ratings.value||null,setlist:fd.get('setlist')||null,notes:fd.get('notes')||null,updated_at:new Date().toISOString()}).eq('id',id);if(error){setError(error.message);return}setEditing(false);await load()}
 async function remove(){if(!confirm('Delete this gig permanently?'))return;const {error}=await supabase.from('gigs').delete().eq('id',id);if(error)setError(error.message);else router.push('/')}
 async function addComment(e:React.FormEvent){e.preventDefault();if(!comment.trim()||!userId)return;const {error}=await supabase.from('comments').insert({gig_id:id,user_id:userId,body:comment.trim()});if(!error){setComment('');await load()}}
 if(loading)return <AuthGuard><Nav/><main className="shell"><Loading label="Finding the ticket…"/></main></AuthGuard>;if(!gig)return <AuthGuard><Nav/><main className="shell"><div className="empty">{error||'Gig not found.'}</div></main></AuthGuard>;const own=gig.user_id===userId;
 return <AuthGuard><Nav/><main className="shell narrow"><section className="hero"><div><div className="eyebrow">// {new Date(gig.event_date+'T00:00:00').toLocaleDateString('en-GB',{dateStyle:'long'})}</div><h1>{gig.artist_name}</h1><p className="hero-copy">{gig.venue_name}{gig.city?`, ${gig.city}`:''}{gig.festival_name?` · ${gig.festival_name}`:''}</p></div>{own&&<div className="button-row"><button className="ghost" onClick={()=>setEditing(!editing)}><Pencil size={16}/> {editing?'Cancel':'Edit'}</button><button className="danger" onClick={remove}><Trash2 size={16}/> Delete</button></div>}</section>
 {editing?<form className="panel" onSubmit={save}><div className="formgrid"><div className="field"><label>Artist</label><input className="input" name="artist" defaultValue={gig.artist_name} required/></div><div className="field"><label>Venue</label><input className="input" name="venue" defaultValue={gig.venue_name} required/></div><div className="field"><label>Festival</label><input className="input" name="festival" defaultValue={gig.festival_name||''}/></div><div className="field"><label>Date</label><input className="input" type="date" name="date" defaultValue={gig.event_date} required/></div><div className="field"><label>Type</label><select className="input" name="event_type" defaultValue={gig.event_type||'gig'}><option value="gig">Gig</option><option value="festival">Festival</option><option value="club-night">Club night</option><option value="comedy">Comedy</option><option value="other">Other</option></select></div><div className="field"><label>City</label><input className="input" name="city" defaultValue={gig.city||''}/></div><div className="field"><label>Country</label><input className="input" name="country" defaultValue={gig.country||''}/></div><div className="field"><label>Ticket URL</label><input className="input" type="url" name="ticket_url" defaultValue={gig.ticket_url||''}/></div>{ratingFields.map(f=><div className="field" key={f}><label>{f} rating</label><Stars value={ratings[f]||0} onChange={n=>setRatings({...ratings,[f]:n})}/></div>)}</div><PhotoUploader userId={userId} urls={photos} onChange={setPhotos}/><div className="field"><label>Setlist</label><textarea className="textarea" name="setlist" defaultValue={gig.setlist||''}/></div><div className="field"><label>Review</label><textarea className="textarea" name="notes" defaultValue={gig.notes||''}/></div><label className="toggle"><input type="checkbox" name="is_public" defaultChecked={gig.is_public!==false}/> Public</label>{error&&<p className="error">{error}</p>}<button className="btn">Save changes</button></form>:
 <><article className="panel detail"><div className="detail-grid"><div><span className="pill">{gig.event_type||'gig'}</span><Stars value={gig.overall_rating}/><p className="note review-text">{gig.notes||'No review added.'}</p>{gig.ticket_url&&<a className="ghost dark inline" href={gig.ticket_url} target="_blank" rel="noreferrer">Ticket page <ExternalLink size={14}/></a>}<p className="meta">Logged by <Link href={`/u/${gig.profiles?.username}`}>{gig.profiles?.display_name||gig.profiles?.username||'fan'}</Link></p></div><div className="rating-list">{[['Performance',gig.performance_rating],['Sound',gig.sound_rating],['Crowd',gig.crowd_rating],['Venue',gig.venue_rating],['Value',gig.value_rating]].map(([k,v])=><div key={String(k)}><span>{k}</span><strong>{v||gig.overall_rating}/5</strong></div>)}</div></div>{gig.photo_urls?.length?<div className="photo-gallery">{gig.photo_urls.map(url=><img key={url} src={url} alt="Gig memory"/>)}</div>:null}{gig.setlist&&<><h3>Setlist</h3><pre className="setlist">{gig.setlist}</pre></>}<LikeButton gigId={gig.id}/></article>
 <section className="panel comments"><h2>Comments <span className="accent">({comments.length})</span></h2>{comments.map(c=><div className="comment" key={c.id}><strong>{c.profiles?.display_name||c.profiles?.username||'Fan'}</strong><span className="meta">{new Date(c.created_at).toLocaleString('en-GB')}</span><p>{c.body}</p></div>)}<form className="comment-form" onSubmit={addComment}><input className="input" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment…"/><button className="btn small">Post</button></form></section></>}
 </main></AuthGuard>}
