'use client';
import { Suspense, useEffect,useState } from 'react'; import { useRouter,useSearchParams } from 'next/navigation'; import { Nav } from '@/components/Nav'; import { AuthGuard } from '@/components/AuthGuard'; import { Stars } from '@/components/Stars'; import { PhotoUploader } from '@/components/PhotoUploader'; import { supabase } from '@/lib/supabase';
const fields=['overall','performance','sound','crowd','venue','value'] as const;
function NewGigForm(){const router=useRouter();const search=useSearchParams();const [userId,setUserId]=useState('');const [photos,setPhotos]=useState<string[]>([]);const [ratings,setRatings]=useState<Record<string,number>>({overall:0,performance:0,sound:0,crowd:0,venue:0,value:0});const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUserId(data.user?.id||''))},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const fd=new FormData(e.currentTarget);if(!userId){setError('Your session expired. Sign in again.');setSaving(false);return}if(!ratings.overall){setError('Choose an overall rating.');setSaving(false);return}const {data,error}=await supabase.from('gigs').insert({user_id:userId,artist_name:fd.get('artist'),venue_name:fd.get('venue'),festival_name:fd.get('festival')||null,event_date:fd.get('date'),event_type:fd.get('event_type')||'gig',city:fd.get('city')||null,country:fd.get('country')||null,ticket_url:fd.get('ticket_url')||null,photo_urls:photos,is_public:fd.get('is_public')==='on',overall_rating:ratings.overall,performance_rating:ratings.performance||null,sound_rating:ratings.sound||null,crowd_rating:ratings.crowd||null,venue_rating:ratings.venue||null,value_rating:ratings.value||null,notes:fd.get('notes')||null,setlist:fd.get('setlist')||null}).select('id').single();setSaving(false);if(error){setError(error.message);return}router.push(`/gigs/${data.id}`)}
 return <AuthGuard><Nav/><main className="shell narrow"><section className="hero"><div><div className="eyebrow">// stamp a new memory</div><h1>LOG A <span className="accent">GIG</span></h1></div></section><form className="panel" onSubmit={submit}><div className="formgrid"><div className="field"><label>Artist / act</label><input className="input" name="artist" defaultValue={search.get('artist')||''} required/></div><div className="field"><label>Venue</label><input className="input" name="venue" defaultValue={search.get('venue')||''} required/></div><div className="field"><label>Festival (optional)</label><input className="input" name="festival"/></div><div className="field"><label>Date</label><input className="input" type="date" name="date" defaultValue={search.get('date')||new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>Type</label><select className="input" name="event_type"><option value="gig">Gig</option><option value="festival">Festival</option><option value="club-night">Club night</option><option value="comedy">Comedy</option><option value="other">Other</option></select></div><div className="field"><label>City</label><input className="input" name="city" defaultValue={search.get('city')||''}/></div><div className="field"><label>Country</label><input className="input" name="country" defaultValue="United Kingdom"/></div><div className="field"><label>Ticket link</label><input className="input" name="ticket_url" type="url" defaultValue={search.get('ticketUrl')||''}/></div>{fields.map(f=><div className="field" key={f}><label>{f} rating</label><Stars value={ratings[f]} onChange={n=>setRatings({...ratings,[f]:n})}/></div>)}</div><PhotoUploader userId={userId} urls={photos} onChange={setPhotos}/><div className="field"><label>Setlist</label><textarea className="textarea" name="setlist" placeholder="One song per line"/></div><div className="field"><label>Review / notes</label><textarea className="textarea" name="notes" placeholder="Highlights, surprises, disasters…"/></div><label className="toggle"><input type="checkbox" name="is_public" defaultChecked/> Show this gig publicly</label>{error&&<p className="error">{error}</p>}<button className="btn" disabled={saving}>{saving?'Stamping…':'Stamp it'}</button></form></main></AuthGuard>}


export default function NewGigPage(){return <Suspense fallback={<main className="shell narrow"><div className="panel">Loading gig form…</div></main>}><NewGigForm/></Suspense>}
